version: "3.5"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
      MYSQL_DATABASE: name
      MYSQL_USER: nongao
      MYSQL_PASSWORD: Password1234
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: ./server/  # Corrected 'buid' to 'build'
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: nongao
      DB_PASSWORD: Password1234
      DB_DATABASE: name
